"""empty message

Revision ID: 14ca4759c49e
Revises: 
Create Date: 2021-04-29 00:03:10.414451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ca4759c49e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarmtable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device', sa.String(length=128), nullable=True),
    sa.Column('typealarm', sa.String(length=128), nullable=True),
    sa.Column('discription', sa.String(length=128), nullable=True),
    sa.Column('solution', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emailalarmtable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricetable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('levelprice01', sa.Float(), nullable=True),
    sa.Column('levelprice02', sa.Float(), nullable=True),
    sa.Column('levelprice03', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sdm220table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('powerfactor', sa.Float(), nullable=True),
    sa.Column('voltage', sa.Float(), nullable=True),
    sa.Column('current', sa.Float(), nullable=True),
    sa.Column('power', sa.Float(), nullable=True),
    sa.Column('enegry', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userlogtable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('operator', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('userlogtable')
    op.drop_table('sdm220table')
    op.drop_table('pricetable')
    op.drop_table('emailalarmtable')
    op.drop_table('alarmtable')
    # ### end Alembic commands ###
