  language: python
  python:
    - "3.8"
  services:
    - postgresql
  before_script:
    - psql -c 'create database powermanagesystem;' -U postgres
  install:
    - pip install pipenv
    - pipenv install
  script:
    - pytest --cov=src --cov-config .coveragerc
  after_success:
    - coveralls
  addons:
    - postgresql: "9.3"
