export const FETCH_ALARM = 'FETCH_ALARM';
export const FETCH_ALARM_SUCCESS = 'FETCH_ALARM_SUCCESS';
export const FETCH_ALARM_FAILED = 'FETCH_ALARM_FAILED';
export const FILTER_ALARM = 'FILTER_ALARM';

// add email alarm
export const ADD_EMAIL_ALARM = 'ADD_EMAIL_ALARM';
export const ADD_EMAIL_ALARM_SUCCESS = 'ADD_EMAIL_ALARM_SUCCESS';
export const ADD_EMAIL_ALARM_FAILED = 'ADD_EMAIL_ALARM_FAILED';

// refesh list email EMAIL_ALARM
export const REFESH_EMAIL_ALARM = 'REFESH_EMAIL_ALARM';
export const REFESH_EMAIL_ALARM_SUCCESS = 'REFESH_EMAIL_ALARM_SUCCESS';
export const REFESH_EMAIL_ALARM_FAILED = 'REFESH_EMAIL_ALARM_FAILED';
