// api main last
export const REFESH_MAIN_LAST = 'REFESH_MAIN_LAST';
export const REFESH_MAIN_LAST_SUCCESS = 'REFESH_MAIN_LAST_SUCCESS';
export const REFESH_MAIN_LAST_FAILED = 'REFESH_MAIN_LAST_FAILED';

// api main 5 min
export const REFESH_MAIN_MIN = 'REFESH_MAIN_MIN';
export const REFESH_MAIN_MIN_SUCCESS = 'REFESH_MAIN_MIN_SUCCESS';
export const REFESH_MAIN_MIN_FAILED = 'REFESH_MAIN_MIN_FAILED';

// api main enegry hourly
export const REFESH_MAIN_ENEGRY_HOURLY = 'REFESH_MAIN_ENEGRY_HOURLY';
export const REFESH_MAIN_ENEGRY_HOURLY_SUCCESS =
  'REFESH_MAIN_ENEGRY_HOURLY_SUCCESS';
export const REFESH_MAIN_ENEGRY_HOURLY_FAILED =
  'REFESH_MAIN_ENEGRY_HOURLY_FAILED';

// api main enegry dayly
export const REFESH_MAIN_ENEGRY_DAYLY = 'REFESH_MAIN_ENEGRY_DAYLY';
export const REFESH_MAIN_ENEGRY_DAYLY_SUCCESS =
  'REFESH_MAIN_ENEGRY_DAYLY_SUCCESS';
export const REFESH_MAIN_ENEGRY_DAYLY_FAILED =
  'REFESH_MAIN_ENEGRYY_DAYLY_FAILED';

// api main enegry weekly
export const REFESH_MAIN_ENEGRY_WEEKLY = 'REFESH_MAIN_ENEGRY_WEEKLY';
export const REFESH_MAIN_ENEGRY_WEEKLY_SUCCESS =
  'REFESH_MAIN_ENEGRY_WEEKLY_SUCCESS';
export const REFESH_MAIN_ENEGRY_WEEKLY_FAILED =
  'REFESH_MAIN_ENEGRY_WEEKLY_FAILED';

// api main enegry monthly
export const REFESH_MAIN_ENEGRY_MONTHLY = 'REFESH_MAIN_ENEGRY_MONTHLY';
export const REFESH_MAIN_ENEGRY_MONTHLY_SUCCESS =
  'REFESH_MAIN_ENEGRY_MONTHLY_SUCCESS';
export const REFESH_MAIN_ENEGRY_MONTHLY_FAILED =
  'REFESH_MAIN_ENEGRY_MONTHLY_FAILED';

// api main enegry hourly
export const REFESH_MAIN_ENEGRY = 'REFESH_MAIN_ENEGRY';
export const REFESH_MAIN_ENEGRY_SUCCESS = 'REFESH_MAIN_ENEGRY_SUCCESS';
export const REFESH_MAIN_ENEGRY_FAILED = 'REFESH_MAIN_ENEGRY_FAILED';

// api house_erea
export const REFESH_HOUSE_AREA = 'REFESH_HOUSE_AREA';
export const REFESH_HOUSE_AREA_SUCCESS = 'REFESH_HOUSE_AREA_SUCCESS';
export const REFESH_HOUSE_AREA_FAILED = 'REFESH_HOUSE_AREA_FAILED';

export const REFESH_POWER_HOUSE_AREA = 'REFESH_POWER_HOUSE_AREA';
export const REFESH_POWER_HOUSE_AREA_SUCCESS =
  'REFESH_POWER_HOUSE_AREA_SUCCESS';
export const REFESH_POWER_HOUSE_AREA_FAILED = 'REFESH_POWER_HOUSE_AREA_FAILED';

// api fish_lake_erea
export const REFESH_FISH_LAKE_AREA = 'REFESH_FISH_LAKE_AREA';
export const REFESH_FISH_LAKE_AREA_SUCCESS = 'REFESH_FISH_LAKE_AREA_SUCCESS';
export const REFESH_FISH_LAKE_AREA_FAILED = 'REFESH_FISH_LAKE_AREA_FAILED';

export const REFESH_POWER_FISH_LAKE_AREA = 'REFESH_POWER_FISH_LAKE_AREA';
export const REFESH_POWER_FISH_LAKE_AREA_SUCCESS =
  'REFESH_POWER_FISH_LAKE_AREA_SUCCESS';
export const REFESH_POWER_FISH_LAKE_AREA_FAILED =
  'REFESH_POWER_FISH_LAKE_AREA_FAILED';

// api solar_01_erea
export const REFESH_SOLAR01_AREA = 'REFESH_SOLAR01_AREA';
export const REFESH_SOLAR01_AREA_SUCCESS = 'REFESH_SOLAR01_AREA_SUCCESS';
export const REFESH_SOLAR01_AREA_FAILED = 'REFESH_SOLAR01_AREA_FAILED';

export const REFESH_POWER_SOLAR01_AREA = 'REFESH_POWER_SOLAR01_AREA';
export const REFESH_POWER_SOLAR01_AREA_SUCCESS =
  'REFESH_POWER_SOLAR01_AREA_SUCCESS';
export const REFESH_POWER_SOLAR01_AREA_FAILED =
  'REFESH_POWER_SOLAR01_AREA_FAILED';

// api solar_02_erea
export const REFESH_SOLAR02_AREA = 'REFESH_SOLAR02_AREA';
export const REFESH_SOLAR02_AREA_SUCCESS = 'REFESH_SOLAR02_AREA_SUCCESS';
export const REFESH_SOLAR02_AREA_FAILED = 'REFESH_SOLAR02_AREA_FAILED';

export const REFESH_POWER_SOLAR02_AREA = 'REFESH_POWER_SOLAR02_AREA';
export const REFESH_POWER_SOLAR02_AREA_SUCCESS =
  'REFESH_POWER_SOLAR02_AREA_SUCCESS';
export const REFESH_POWER_SOLAR02_AREA_FAILED =
  'REFESH_POWER_SOLAR02_AREA_FAILED';

// api refesh caculator enegry
export const REFESH_CALCULATOR_ENEGRY = 'REFESH_CALCULATOR_ENEGRY';
export const REFESH_CALCULATOR_ENEGRY_SUCCESS =
  'REFESH_CALCULATOR_ENEGRY_SUCCESS';
export const REFESH_CALCULATOR_ENEGRY_FAILED =
  'REFESH_CALCULATOR_ENEGRY_FAILED';

// api refesh main caculator enegry
export const REFESH_MAIN_CALCULATOR_ENEGRY = 'REFESH_MAIN_CALCULATOR_ENEGRY';
export const REFESH_MAIN_CALCULATOR_ENEGRY_SUCCESS =
  'REFESH_MAIN_CALCULATOR_ENEGRY_SUCCESS';
export const REFESH_MAIN_CALCULATOR_ENEGRY_FAILED =
  'REFESH_MAIN_CALCULATOR_ENEGRY_FAILED';
